on:
  push:
  pull_request:

name: run_script

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: install.packages(c("pracma", "magrittr", "dplyr"))
        shell: Rscript {0}

      - name: Run script 
        run: Rscript labrecque_and_swanson_2018.R

      - name: Upload table to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: table_1.csv
          path: table_1.csv

